-- liquibase formatted sql

-- changeSet Vladislav:1
drop table feed_images;

create table feed_images(
    id int generated by default as identity primary key,
    feed_id int references feed(id) on delete cascade,
    url varchar
);
-- rollback drop table feed_images;