-- liquibase formatted sql

-- changeSet Danil:1
create table score(
    id int generated by default as identity primary key,
    score int,
    person_id int references person(id)
)
-- rollback drop table score;