-- liquibase formatted sql

-- changeSet Vladislav:8
drop table friend_request;

create table friend_request(
    id int generated by default as identity,
    person_from int references person(id),
     person_to int references person(id),
     exp_date date not null
)
-- rollback drop table friend_request;

