-- liquibase formatted sql

-- changeSet Vladislav:2
create table feed(
    id int generated by default as identity primary key,
    person_id int references person(id),
    body varchar(1000)
);
-- rollback drop table feed;