-- liquibase formatted sql

-- changeSet Vladislav:3
create table feed_images(
    id int generated by default as identity primary key,
    feed_id int references feed(id),
    url varchar
);
-- rollback drop table feed_images;